"""empty message

Revision ID: 9ce4ff3fb5d2
Revises: 8bc154db3519
Create Date: 2021-10-20 15:38:07.671457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b50be9f7b2'
down_revision = '8bc154db3519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
