"""empty message

Revision ID: c883fa54504e
Revises: f62ebc0600a0
Create Date: 2021-10-20 19:06:41.822958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c883fa54504e'
down_revision = 'f62ebc0600a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('title', sa.String(length=500), nullable=False))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'title')
    # ### end Alembic commands ###
