"""empty message

Revision ID: db5e5619d154
Revises: dacfdff4b4ab
Create Date: 2021-11-18 18:32:45.297495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5e5619d154'
down_revision = 'dacfdff4b4ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'reviews', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='unique')
    # ### end Alembic commands ###
